main:
  - name: Dropdown
    weight: 30
  - parent: Dropdown
    name: Lorem dolor
    weight: 31
  - parent: Dropdown
    name: Magna Phasellus
    weight: 32
  - parent: Dropdown
    name: Etiam sed tempus
    weight: 33
  - parent: Dropdown
    name: Submenu
    weight: 34
  - parent: Submenu
    name: Lorem dolor
    identifier: sub-lorem
    weight: 35
  - parent: Submenu
    name: Phasellus magna
    weight: 36
  - parent: Submenu
    name: Magna phasellus
    weight: 37
  - parent: Submenu
    name: Etiam nisl
    weight: 38
  - parent: Submenu
    name: Veroeros feugiat
    identifier: sub-veroeros
    weight: 39
  - parent: Dropdown
    name: Veroeros feugiat
    weight: 40
