main:
  - identifier: home
    name: Home
    parent: Home
    pageRef: /
    weight: 10

  - identifier: store
    name: Shop
    parent: Shop
    pageRef: /shop
    weight: 20

  - identifier: posts
    name: Posts
    parent: Posts
    pageRef: /posts
    weight: 30

  - identifier: videos
    name: Videos
    parent: Videos
    pageRef: /videos
    weight: 40

  - identifier: audioTracks
    parent: Audio Tracks
    name: Audio Tracks
    pageRef: /audio
    weight: 50

  - identifier: artwork
    parent: Artwork
    name: Artwork
    pageRef: /art
    weight: 60
