baseURL: /
languageCode: en-us
title: Travis Damion

DefaultContentLanguage: en
languages:
  en:
    title: My New Hugo i18n Site
    languageName: English
    weight: 1
  gr:
    title: Η Νεα μου Ιστιοσελιδα
    languageName: Greek
    weight: 2

  
